network:
  name: resnet18

  # Specify a folder containing a pre-trained model to fine-tune. If training from scratch, pass None.
  fine_tune_from: 'resnet-18_40-epochs'

  projection_head:
    mlp_hidden_size: 4096
    projection_size: 256

data_transforms:
  s: 1
  input_shape: (32,32,3)

trainer:
  batch_size: 192
  m: 0.99 # momentum update
  checkpoint_interval: 5000
  max_epochs: 100
  num_workers: 16

optimizer:
  params:
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.0001
